export default {
  status: "OK",
  request_id: "0ce198af-5501-41f8-bc9f-58e7d2add71d",
  data: {
    symbol: "AAPL:NASDAQ",
    name: "Apple Inc",
    type: "stock",
    price: 151.29,
    open: 152.305,
    high: 152.7,
    low: 149.97,
    volume: 74829573,
    previous_close: 150.72,
    change: 0.57,
    change_percent: 0.3782,
    pre_or_post_market: 150.88,
    pre_or_post_market_change: -0.41,
    pre_or_post_market_change_percent: -0.271,
    last_update_utc: "2022-11-19 01:00:00",
    country_code: "US",
    exchange: "NASDAQ",
    exchange_open: "2022-11-18 09:30:00",
    exchange_close: "2022-11-18 16:00:00",
    timezone: "America/New_York",
    utc_offset_sec: -18000,
    currency: "USD",
    about:
      "Apple Inc. is an American multinational technology company headquartered in Cupertino, California, United States. Apple is the largest technology company by revenue and, as of June 2022, is the world's biggest company by market capitalization, the fourth-largest personal computer vendor by unit sales and second-largest mobile phone manufacturer. It is one of the Big Five American information technology companies, alongside Alphabet, Amazon, Meta, and Microsoft.\nApple was founded as Apple Computer Company on April 1, 1976, by Steve Jobs, Steve Wozniak and Ronald Wayne to develop and sell Wozniak's Apple I personal computer. It was incorporated by Jobs and Wozniak as Apple Computer, Inc. in 1977 and the company's next computer, the Apple II, became a best seller and one of the first mass-produced microcomputers. Apple went public in 1980 to instant financial success. The company developed computers featuring innovative graphical user interfaces, including the 1984 original Macintosh, announced that year in a critically acclaimed advertisement. By 1985, the high cost of its products and power struggles between executives caused problems.",
    year_low: 129.04,
    year_high: 182.94,
    primary_exchange: "NASDAQ",
    company_website: "http://www.apple.com/",
    company_country_code: "US",
    company_country: "United States",
    company_state: "California",
    company_city: "Cupertino",
    company_street_address: "One Apple Park Way",
    company_ceo: "Tim Cook",
    company_employees: 164000,
    company_cdp_score: "A-",
    company_founded_date: "1976-04-01",
    company_cdp_url: "https://www.cdp.net/en/responses/865",
    avg_volume: 89998949,
    company_pe_ratio: 24.7481,
    company_market_cap: 2406739367994.995,
    company_dividend_yield: 0.6081,
    wikipedia_url: "https://en.wikipedia.org/wiki/Apple_Inc.",
    google_mid: "/m/07zmbvf",
  },
};
